### ISSUE TITLE
How to make hybrid assembly of a viral genome

### ISSUE THREAD

**Issue by sekhwal** [hzi-bifo/Haploflow#13]
Hi, I am looking to make Hybrid assembly of a viral genome. I have got paired-end reads from Illumina and long reads from MinION from a viral sample. Please suggest if I can use Haploflow for viral hybrid genome assembly. Also, please let me know if I need to trim the data before making assembly.

Thank you!

**Comment by AlphaSquad** [comment]
Haploflow has no specific mode for long or short reads. If the depth of your short reads is high enough, it is likely that the assembly is better with just using the short reads (since they have less errors).
If you want to use both, you would need to append all read files into a single `fastq` and provide it to Haploflow

**Comment by sekhwal** [comment]
Actually, I am looking to get full genome of virus. Therefore, I need long reads of MinION in this order.
