### ISSUE TITLE
install and test data processing

### ISSUE THREAD

**Issue by antoine4ucsd** [hzi-bifo/Haploflow#15]
Hello
I am very interesting in working with haploflow on our sequencing data (HIV and SIV).
I was able to install haploflow via conda on my Mac M1.
within the haploflow folder I ran
```
haploflow ./HIV_3_toy.fq --read-file HIV_3_toy.fq  --out test --log test/log
```
it creates a test folder which contains:
```
ls
Cov.tsv		contigs.fa	log
```
no error message BUT no graph or coverage subfolder or files??? it took 23'' to run. I am attaching the log.
I also tried to install haploflow on my mac using build but it failed:
```
make
Scanning dependencies of target haploflow
[ 16%] Building CXX object CMakeFiles/haploflow.dir/main.cpp.o
In file included from ~/anaconda2/gcc/include/c++/unordered_map:38:0,
                 from ~/Haploflow/deBruijnGraph.h:4,
                 from ~/Haploflow/main.cpp:1:
~/anaconda2/gcc/include/c++/type_traits:38:28: fatal error: bits/c++config.h: No such file or directory
```

since I also have access to a linux server, I tried to install it but I got this error message:
```
conda install -c bioconda haploflow
Package libgcc-ng conflicts for:
python=3.8 -> libgcc-ng[version='>=7.3.0|>=7.5.0']
python=3.8 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=7.2.0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.28=0
  - haploflow -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - python=3.8 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.28
```
what would you recommend?
I would like to move forward with all your nice complementary code but I want to make sure eveything is set up properly first

thank you!

**Comment by AlphaSquad** [comment]
Hi, let me try to answer your questions:
1. The output looks okay (you did not link the log so I cannot check in more detail) - as long as there really are contigs in the fasta file? I changed Haploflow such that it does not print all graph and coverage files per default (because it could be many), so you need to run Haploflow with the `--debug` option for them to appear (by default it is only the coverage distribution of the highest abundant connected component)
2. We only tested Haploflow on Linux, so unfortunately it is possible that it just will not run on mac, sorry.
3. As for the build error: This is very hard to debug - is that in a new/"empty" conda environment? If not, you could try to create a new environment without any packages and install Haploflow afterwards. Haploflow itself does not really need python3.8 so I kind of do not see the connection here

**Comment by antoine4ucsd** [comment]
thank you. I get it
It is working on my Mac M1 but not on my linux server. that will be ok for me. 
I just need to optimize the parameters for our data to get a representative set of haplotypes. I saw you suggested to have  the --strict option set to zero for data when you expect low freq variants, which is our case (SIV and HIV). 
any other recommendations and settings you'd suggest f?

for now I am doing the following:
```
haploflow --read-file ./data.fastq   --strict 0
quast # version quast-5.1.0r, no changes in settings
minimap2 -x map-ont -O 4 -E 2.0 # to get the bam file
python create_full_length_virus.py  contigs.fa  reference.fasta contigs.used_snps contigs.coords report.tsv contigs.bam .
```

thank you again for being so responsive!

**Comment by AlphaSquad** [comment]
I usually recommend to run Haploflow with a stricter setting first to have a "baseline" of contigs. Using `--strict 0` _can_ result in a lot of contigs depending on the sequencing depth and quality and if you run it with a little stricter setting first then you can compare more easily - it is even possible that there is no real difference.

**Comment by antoine4ucsd** [comment]
make sense
thank you again

**Comment by AlphaSquad** [comment]
Closing this for now, feel free to re-open or open a new issue
